{% set name = "lume-base" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad9384dba8757eaad5e0f9188c8aac405355cb2d40923203a903533d5a64d684

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - openpmd-beamphysics
    - pyyaml

test:
  imports:
    - lume.base

about:
  home: https://github.com/slaclab/lume-base
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Base classes and architecture for LUME Python projects
  description: |
    Base classes and architecture for LUME Python projects
  doc_url: https://slaclab.github.io/lume-base
  dev_url: https://github.com/slaclab/lume-base

extra:
  recipe-maintainers:
    - hhslepicka
    - ChristopherMayes
    - jacquelinegarrahan
