{% set name = "lume-base" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ead97b1d51226abea1a1923969c4255b1c7e55a8340be0e4d2923256e54dc5f3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - openpmd-beamphysics
    - pyyaml

test:
  imports:
    - lume.base

about:
  home: https://github.com/slaclab/lume-base
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Base classes and architecture for LUME Python projects
  description: |
    Base classes and architecture for LUME Python projects
  doc_url: https://slaclab.github.io/lume-base
  dev_url: https://github.com/slaclab/lume-base

extra:
  recipe-maintainers:
    - hhslepicka
    - ChristopherMayes
    - jacquelinegarrahan
